apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: ${WORKER_NAME}
  namespace: default
  labels:
    kueue.x-k8s.io/queue-name: ${QUEUE_NAME}
spec:
  suspend: true
  failurePolicy:
    maxRestarts: 1
    restartStrategy: Recreate
  network:
    enableDNSHostnames: true
    publishNotReadyAddresses: true
  replicatedJobs:
  - name: worker
    replicas: 1 # We run 1 slice per JobSet
    template:
      spec:
        backoffLimit: 1000000
        completionMode: Indexed
        completions: ${VMS_PER_SLICE}
        parallelism: ${VMS_PER_SLICE}
        template:
          metadata:
            annotations:
              alpha.jobset.sigs.k8s.io/exclusive-topology: cloud.google.com/gke-nodepool
          spec:
            containers:
            - name: pathways-worker
              image: ${SERVER_IMAGE}
              imagePullPolicy: Always
              args:
              - --server_port=29005
              - --resource_manager_address=${PATHWAYS_RM_SERVICE_ADDRESS}
              - --gcs_scratch_location=${GCS_SCRATCH_LOCATION}
              - --cloud_pathways_sidecar_shm_directory=${SIDECAR_SHM_DIR}
              env:
              - name: TPU_MIN_LOG_LEVEL
                value: "0"
              - name: TF_CPP_MIN_LOG_LEVEL
                value: "0"
              - name: XCLOUD_ENVIRONMENT
                value: GCP
              - name: MEGASCALE_GRPC_ENABLE_XOR_TRACER
                value: "false"
              - name: MEGASCALE_NUM_SLICES
                value: "1" # Each JobSet is 1 slice
              - name: JOBSET_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.annotations['jobset.sigs.k8s.io/jobset-name']
              - name: REPLICATED_JOB_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.annotations['jobset.sigs.k8s.io/replicatedjob-name']
              - name: MEGASCALE_SLICE_ID
                value: "0" # Only 1 slice in this JobSet
              - name: PATHWAYS_HEAD
                value: pathways-rm-service
              - name: MEGASCALE_COORDINATOR_ADDRESS
                value: pathways-rm-service
              ports:
              - containerPort: 29005
                protocol: TCP
              - containerPort: 29006
                protocol: TCP
              - containerPort: 8471
                protocol: TCP
              - containerPort: 8080
                protocol: TCP
              resources:
                limits:
                  google.com/tpu: "${CHIPS_PER_VM}"
              volumeMounts:
              - name: shared-tmp
                mountPath: /tmp
              - name: sidecar-shared-memory
                mountPath: ${SIDECAR_SHM_DIR}
            initContainers:
            - name: colocated-python-sidecar
              image: ${SIDECAR_IMAGE}
              imagePullPolicy: Always
              env:
              - name: GRPC_SERVER_ADDRESS
                value: '0.0.0.0:50051'
              - name: CLOUD_PATHWAYS_SIDECAR_SHM_DIRECTORY
                value: ${SIDECAR_SHM_DIR}
              - name: PYTHONUNBUFFERED
                value: '1'
              - name: LOGLEVEL
                value: 'DEBUG'
              - name: GLOG_minloglevel
                value: '0'
              - name: GLOG_v
                value: '5'
              - name: TF_CPP_MIN_LOG_LEVEL
                value: '0'
              - name: TF_CPP_MIN_VLOG_LEVEL
                value: '5'
              - name: TPU_MIN_LOG_LEVEL
                value: '0'
              - name: GLOG_vmodule
                value: 'jax_array_handlers=5,type_handlers=5,tensorstore_utils=5'
              ports:
              - containerPort: 50051
                protocol: TCP
              resources: {}
              restartPolicy: Always
              volumeMounts:
              - name: shared-tmp
                mountPath: /tmp
              - name: sidecar-shared-memory
                mountPath: ${SIDECAR_SHM_DIR}
            dnsPolicy: ClusterFirstWithHostNet
            hostNetwork: true
            nodeSelector:
              cloud.google.com/gke-tpu-accelerator: ${ACCELERATOR_LABEL}
              cloud.google.com/gke-tpu-topology: ${TOPOLOGY}
            restartPolicy: OnFailure
            volumes:
            - name: shared-tmp
              hostPath:
                path: /tmp
                type: DirectoryOrCreate
            - name: sidecar-shared-memory
              emptyDir:
                medium: Memory
  startupPolicy:
    startupPolicyOrder: InOrder
  successPolicy:
    operator: All
